### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libxgd_ddi_jni.so" not found

### ISSUE THREAD

**Issue by gsachdeva** [judahben149/EMVSync#1]
I am facing this issue and not able to find the missing library

**Comment by judahben149** [comment]
Are you facing this when building the project or running the application?

**Comment by gsachdeva** [comment]
It's coming while starting of the application

**Comment by gsachdeva** [comment]
Process: com.judahben149.emvsync, PID: 23739
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libxgd_ddi_jni.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.xinguodu.ddiinterface.Ddi.<clinit>(Ddi.java:38)
        at com.xinguodu.ddiinterface.Ddi.ddi_ddi_sys_init(Native Method)
        at com.nexgo.oaf.apiv3.b.<clinit>(DeviceEngineImpl.java:60)
        at com.nexgo.oaf.apiv3.APIProxy.getDeviceEngine(APIProxy.java:21)
        at com.judahben149.emvsync.MainApp.onCreate(MainApp.kt:30)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by judahben149** [comment]
Okay, this is expected.
Because the app is bundled with the Nexgo SDK library, you cannot run the app on a regular Android device.
You can only run it on a Nexgo POS terminal device.

**Comment by gsachdeva** [comment]
@judahben149 Is there any way to run this application on Emulator or Android device ? If not then what is the other way to check the application?

**Comment by judahben149** [comment]
That will be difficult to achieve.
This is because at almost all parts of the app, it communicates with the Nexgo kernel

However, you can try to comment out some of the sdk-specific functions such as the emvHandler and deviceEngine. This should be enough to run the app at least, but you will not be able to progress past the main screen

**Comment by gsachdeva** [comment]
Yes, I have done it but it's not working further after 1st screen. BTW, Its nice the application

**Comment by judahben149** [comment]
Yeah, I left out that the commenting was to be done in the application class.

You can navigate to Purchase and settings. Other screens are more tightly integrated.
Thanks for checking it out.

**Comment by gsachdeva** [comment]
I want to check the functionality of Packing and Unpacking of Transactions details into ISO 8583 ....Could you recommend the files to go through that?

**Comment by judahben149** [comment]
Check out Transaction Usecase and KeyExchange Handler.
